language: rust
matrix:
    fast_finish: true
    allow_failures:
        - rust: nightly
    include:
        - rust: stable

        # android
        - rust: stable
          env: TARGET=aarch64-linux-android
          install: rustup target add "$TARGET"
          # disable default-tls feature since cross-compiling openssl is dragons
          script: cargo build --target "$TARGET" --no-default-features

sudo: false
dist: trusty

env:
  global:
    - REQWEST_TEST_BODY_FULL=1

script:
  - cargo build $FEATURES
  - cargo test -v $FEATURES
